# Generated by Django 5.0.6 on 2025-07-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
