# Generated by Django 5.2.4 on 2025-07-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_author'),
        ('todo', '0002_task_priority'),
    ]

    operations = [
    ]
